// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgnpegknyyqsyvpofkrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnbnBlZ2tueXlxc3l2cG9ma3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMzM4NjIsImV4cCI6MjA3NDYwOTg2Mn0.ajlXSoymItmhxop0DSyzruasAblheQFdIWbRmq-PZpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});